[package]
name = "sander"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
colors-transform = "0.2.11"
ggegui = "0.3.8"
ggez = "0.9.3"
itertools = "0.12.0"
rand = "0.8.5"
