name: Rust

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

env:
  CARGO_TERM_COLOR: always

jobs:
  build:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install alsa
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev

    - name: Install udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev

    - name: Run cargo check --all-targets w/ -D warnings
      run: cargo check --all-targets
      env:
        RUSTFLAGS: "-D warnings"

    - name: Run cargo test w/ -D warnings
      run: cargo test --verbose
      env:
        RUSTFLAGS: "-D warnings"

    - name: Test documentation
      run: cargo test -p doc_tests

  rustfmt:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Get Rust toolchain with rustfmt
      uses: dtolnay/rust-toolchain@stable
      with:
        components: rustfmt

    - name: Run cargo fmt --all -- --check
      run: cargo fmt --all -- --check

  clippy:

    runs-on: ubuntu-latest

    steps:

    - name: Checkout
      uses: actions/checkout@v4

    - name: Install alsa
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libasound2-dev

    - name: Install udev
      run: sudo apt-get update; sudo apt-get install --no-install-recommends libudev-dev

    - name: Run cargo clippy --all-targets --package sander -- -D warnings
      run: cargo clippy --all-targets --package sander -- -D warnings
